id = "lotioncode"
name = "LotionCode"
description = "The open source coding agent."
version = "1.1.49"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/lotioncode"

[agent_servers.lotioncode]
name = "LotionCode"
icon = "./icons/lotioncode.svg"

[agent_servers.lotioncode.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/lotioncode/releases/download/v1.1.49/lotioncode-darwin-arm64.zip"
cmd = "./lotioncode"
args = ["acp"]

[agent_servers.lotioncode.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/lotioncode/releases/download/v1.1.49/lotioncode-darwin-x64.zip"
cmd = "./lotioncode"
args = ["acp"]

[agent_servers.lotioncode.targets.linux-aarch64]
archive = "https://github.com/anomalyco/lotioncode/releases/download/v1.1.49/lotioncode-linux-arm64.tar.gz"
cmd = "./lotioncode"
args = ["acp"]

[agent_servers.lotioncode.targets.linux-x86_64]
archive = "https://github.com/anomalyco/lotioncode/releases/download/v1.1.49/lotioncode-linux-x64.tar.gz"
cmd = "./lotioncode"
args = ["acp"]

[agent_servers.lotioncode.targets.windows-x86_64]
archive = "https://github.com/anomalyco/lotioncode/releases/download/v1.1.49/lotioncode-windows-x64.zip"
cmd = "./lotioncode.exe"
args = ["acp"]
